version: '3.3'

networks:
    redis-cluster-net:
        external:
            name: redis-cluster-net

services:
  database:
    platform: linux/x86_64
    image: oilrmutp57/mysql5.7:1.0
    container_name: sharding-mysql57
    environment:
      MYSQL_ROOT_USER: 'root'   
      MYSQL_ROOT_PASSWORD: '123456'
      SET_CONTAINER_TIMEZONE: 'true'
      CONTAINER_TIMEZONE: 'Asia/Shanghai'     
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './.mysql-data/db:/var/lib/mysql'
      - './conf/my.cnf:/etc/mysql/my.cnf'
      - './init:/docker-entrypoint-initdb.d'
    command:
      #id唯一
      --server_id=100
      --log-bin=mysql-bin
      --sync_binlog=1
      --binlog-ignore-db=mysql
      --binlog_format=row
      --expire_logs_days=7
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    networks:
      redis-cluster-net:
          ipv4_address: 192.168.200.214
